### ISSUE TITLE
syntax error, unexpected token "endif", expecting end of file

### ISSUE THREAD

**Issue by mafinta** [Anamcoollzz/laravel-9-template#2]
Error saat mengganti tampilan login ke "tampilan 2".

C:\project\laravel-9-template-master-stisla\resources\views\stisla\auth\login\index2.blade.php: 47

Register akun di halaman register juga blank response.

**Comment by Anamcoollzz** [comment]
Yang register blank ada bisa bantu screenrecord nya? @alfintashim

**Comment by mafinta** [comment]
![Uploading 2EBC79F5-0060-4675-ACF3-844AD134F4AE.jpeg…]()

Blank setelah tekan daftar. Dan akun pun tidak ada masuk ke database. dan masih di url http://127.0.0.1:8000/auth/register

**Comment by alfintashim** [comment]
![Uploading 88E0BC17-0E65-4003-BFE2-E9DF9A0EE82D.jpeg…]()

**Comment by Anamcoollzz** [comment]
Gambarnya belum berhasil terupload @alfintashim

**Comment by alfintashim** [comment]
https://photos.app.goo.gl/kw43QuXCmAo6XGPX9

**Comment by mafinta** [comment]
> Gambarnya belum berhasil terupload @alfintashim

https://photos.app.goo.gl/kw43QuXCmAo6XGPX9

**Comment by Anamcoollzz** [comment]
DI aku aman mas, bisa screen record mungkin @alfintashim

**Comment by mafinta** [comment]
> DI aku aman mas, bisa screen record mungkin @alfintashim

https://photos.app.goo.gl/hJt1MisKCFuMqiLS6

**Comment by alfintashim** [comment]
Jika gambar gambar (image) tidak muncul, bagian mana yang perlu di fix ya bang?

**Comment by mafinta** [comment]
![52B5F20C-DB51-42DE-97F0-3472861DE1C1](https://user-images.githubusercontent.com/60909622/228164696-d85db387-e40a-4b09-afc6-8f0e270fe05a.jpeg)

kalau semua image di semua posisi tidak ada yang muncul (termasuk halaman login dsb), yang perlu di fix dimana ya bang?
