### ISSUE TITLE
Beberapa menu tidak bisa di akses, ex user-management

### ISSUE THREAD

**Issue by opusoctopus** [Anamcoollzz/laravel-9-template#4]
Selamat sore...

saya menemukan beberapa menu yang ga bisa di akses, mungkin karena keterbatasan pengentahuan saya
kira-kira apa yang perlu di fix bang
udah saya ss bug nya.

Thanks

![image](https://user-images.githubusercontent.com/6553737/236429030-4fb74a63-e20f-42ce-975e-d318c6010ff9.png)

**Comment by faisalachmadf** [comment]
$this->viewFolder            = 'user-management';
 
 masukan itu di usermanagementController nya di function _construct()

**Comment by Anamcoollzz** [comment]
Sudah diupdate ya guys, thanks atas reviewnya @faisalachmadf @opusoctopus

**Comment by opusoctopus** [comment]
Thanks bro....
